module.exports = {
    // adventure: require('./adventure'),
    // orbs: require('./orbs'),
    // perks: require('./perks'),
    antiCopy: require('./antiCopy'),
    bank: require('./bank'),
    // booster: require('./booster'),
    // caseOpening: require('./caseOpening'),
    // clan: require('./clan'),
    // deleteparticle: require('./deleteparticle'),
    disguise: require('./disguise'),
    // edgeBlacksmith: require('./edgeBlacksmith'),
    // friends: require('./friends'),
    // hopper: require('./hopper'),
    itemSign: require('./itemSign'),
    // jail: require('./jail'),
    // lottery: require('./lottery'),
    mapInfo: require('./mapInfo'),
    prefix: require('./prefix'),
    // profile: require('./profile'),
    // ptime: require('./ptime'),
    punishment: require('./punishment'),
    spawner: require('./spawner'),
    // specialPotions: require('./specialPotions'),
    startJail: require('./startJail'),
    status: require('./status'),
    teleporter: require('./teleporter'),
    // trails: require('./trails'),
    vote: require('./vote')
}
