module.exports = {
    npc: require('npc'),
    // perks: require('perks'),
    antiCopy: require('antiCopy'),
    bank: require('bank'),
    // booster: require('booster'),
    // caseOpening: require('caseOpening'),
    // clan: require('clan'),
    deleteparticle: require('deleteparticle'),
    disguise: require('disguise'),
    // friends: require('friends'),
    // hopper: require('hopper'),
    // jail: require('jail'),
    mapInfo: require('mapInfo'),
    // prefix: require('prefix'),
    // profile: require('profile'),
    // spawner: require('spawner'),
    // specialPotions: require('specialPotions'),
    startkick: require('startkick'),
    status: require('status'),
    // trails: require('trails'),
    vote: require('vote')
}
