module.exports = {
    npc: require('./npc'),
    // perks: require('./perks'),
    antiCopy: require('./antiCopy'),
    bank: require('./bank'),
    // booster: require('./booster'),
    // caseOpening: require('./caseOpening'),
    // clan: require('./clan'),
    // deleteparticle: require('./deleteparticle'),
    disguise: require('./disguise'),
    // friends: require('./friends'),
    // hopper: require('./hopper'),
    // jail: require('./jail'),
    mapInfo: require('./mapInfo'),
    // prefix: require('./prefix'),
    // profile: require('./profile'),
    punishment: require('./punishment'),
    // spawner: require('./spawner'),
    // specialPotions: require('./specialPotions'),
    startJail: require('./startJail'),
    status: require('./status'),
    // trails: require('./trails'),
    vote: require('./vote')
}
