module.exports = {
    plot: require('./plot'),
    antiAfk: require('./antiAfk'),
    chat: require('./chat'),
    ggauth: require('./ggauth'),
    globalChat: require('./globalChat'),
    home: require('./home'),
    itemClear: require('./itemClear'),
    mobRemover: require('./mobRemover'),
    money: require('./money'),
    mysteryMod: require('./mysteryMod'),
    near: require('./near'),
    playerUtils: require('./playerUtils'),
    privateChat: require('./privateChat'),
    serverInfo: require('./serverInfo'),
    shutdown: require('./shutdown'),
    spawn: require('./spawn'),
    switcher: require('./switcher'),
    tpa: require('./tpa'),
    warp: require('./warp'),
}
