module.exports = {
    plot: require('./plot'),
    afk: require('./afk'),
    chat: require('./chat'),
    ggauth: require('./ggauth'),
    globalChat: require('./globalChat'),
    homes: require('./homes'),
    ignore: require('./ignore'),
    itemClear: require('./itemClear'),
    mobRemover: require('./mobRemover'),
    money: require('./money'),
    mysteryMod: require('./mysteryMod'),
    near: require('./near'),
    playerUtils: require('./playerUtils'),
    privateChat: require('./privateChat'),
    serverInfo: require('./serverInfo'),
    shutdown: require('./shutdown'),
    slowChat: require('./slowChat'),
    spawn: require('./spawn'),
    switch: require('./switch'),
    teleport: require('./teleport'),
    tpa: require('./tpa'),
    warp: require('./warp'),
}
